const MIN_PHONE_NUMBER_LENGTH = 7;
const TOKEN_LENGTH = 20;
const TOKEN_VALIDITY_TIME = 60 * 60 * 1000; // 1 hour in ms
const MIN_CHECK_TIMEOUT = 1;
const MAX_CHECK_TIMEOUT = 5;
const MAX_CHECK_LENGTH = 5;

module.exports = {
  MIN_PHONE_NUMBER_LENGTH,
  TOKEN_LENGTH,
  TOKEN_VALIDITY_TIME,
  MIN_CHECK_TIMEOUT,
  MAX_CHECK_TIMEOUT,
  MAX_CHECK_LENGTH,
};